Repository tweag/rules_haskell, pull requests merged in 2023-08, with the labels that each got.

#1928 Remove the "Build & Test - Cross" CI job
  .github/workflows/workflow.yaml
Labels: merge-queue

#1926 Do not skip worker on Windows
  .bazelrc.common
  tools/worker/BUILD.bazel
Labels: merge-queue, os:windows, dist:bindist

#1934 Remove unneeded workaround and enable tests on Windows
  rules_haskell_tests/MODULE.bazel
  rules_haskell_tests/ghcide-snapshot.json
  rules_haskell_tests/non_module_deps_2.bzl
  rules_haskell_tests/tests/haskell_proto_simple/BUILD.bazel
Labels: merge-queue

#1918 Nix-based haskell toolchains
  .github/workflows/workflow.yaml
  extensions/haskell_toolchains.bzl
  haskell/ghc_bindist.bzl
  rules_haskell_nix/MODULE.bazel
  rules_haskell_nix/extensions/BUILD.bazel
  rules_haskell_nix/extensions/nix_haskell_toolchains.bzl
  rules_haskell_nix/nixpkgs.bzl
  rules_haskell_nix/non_module_deps.bzl
  rules_haskell_nix/private/BUILD
  rules_haskell_nix/private/declare_toolchains.bzl
  rules_haskell_tests/MODULE.bazel
  rules_haskell_tests/non_module_deps_bzlmod.bzl
  tutorial/MODULE.bazel
Labels: merge-queue

#1935 Retry uploading build events more often
  .bazelrc.common
  .github/workflows/workflow.yaml
Labels: merge-queue, os:windows

#1943 Do not pass linker for object merging on Windows
  .github/workflows/patch-test.yaml
  haskell/cc.bzl
  start
Labels: merge-queue

#1944 Add workflow to update GHC bindists
  .github/update-ghc.py
  .github/workflows/update-ghc.yaml
  haskell/private/workspace_utils.bzl
Labels: merge-queue

#1945 Use a JSON file to keep GHC bindist information
  .github/update-ghc.py
  .github/workflows/update-ghc.yaml
  extensions/haskell_toolchains.bzl
  haskell/BUILD.bazel
  haskell/gen_ghc_bindist.py
  haskell/ghc_bindist.bzl
  haskell/private/ghc_bindist_generated.bzl
  haskell/private/ghc_bindist_generated.json
Labels: merge-queue

#1938 Upgrade rules_cc, platforms and aspect_rules_js to fix Bazel CI HEAD
  MODULE.bazel
  haskell/private/versions.bzl
  haskell/repositories.bzl
  rules_haskell_tests/MODULE.bazel
  start
Labels: merge-queue

#1947 Add `-hide-all-packages` and `-no-user-package-db` to hie bios
  haskell/repl.bzl
Labels: merge-queue
